name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # Opt into Node.js 24 for GitHub Actions

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Cython and Buildozer
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.33
          pip install buildozer
      
      - name: Build APK
        run: buildozer -v android debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: ./bin/*.apk
